export const Data = [
  {
    name: "Strawberry",
    outliers: {
      Sweetness: [0, 1],
      Sourness: [],
      Saltiness: [3],
      Bitterness: [4, 3],
      Savoriness: [2, 3],
      Fatness: [1, 2],
      Astringency: [3],
      Aromaticity: [5],
      Texture: [],
      Piquancy: [3, 2],
    },
    distribution: {
      Sweetness: {
        0: { count: 1, percent: 1.9 },
        1: { count: 1, percent: 1.9 },
        2: { count: 5, percent: 9.6 },
        3: { count: 26, percent: 50 },
        4: { count: 15, percent: 28.8 },
        5: { count: 4, percent: 7.7 },
        unanimity: 0.3,
        agreement: 51.5,
      },
      Sourness: {
        0: { count: 9, percent: 17.3 },
        1: { count: 5, percent: 9.6 },
        2: { count: 15, percent: 28.8 },
        3: { count: 21, percent: 40.4 },
        4: { count: 2, percent: 3.8 },
        5: { count: 0, percent: 0 },
        unanimity: 0.2,
        agreement: 46.3,
      },
      Saltiness: {
        0: { count: 46, percent: 88.5 },
        1: { count: 5, percent: 9.6 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 1.9 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.8,
        agreement: 66.7,
      },
      Bitterness: {
        0: { count: 42, percent: 80.8 },
        1: { count: 8, percent: 15.4 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 1.9 },
        4: { count: 1, percent: 1.9 },
        5: { count: 0, percent: 0 },
        unanimity: 0.7,
        agreement: 57.5,
      },
      Savoriness: {
        0: { count: 44, percent: 84.6 },
        1: { count: 3, percent: 5.8 },
        2: { count: 2, percent: 3.8 },
        3: { count: 3, percent: 5.8 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.7,
        agreement: 55.6,
      },
      Fatness: {
        0: { count: 49, percent: 94.2 },
        1: { count: 2, percent: 3.8 },
        2: { count: 1, percent: 1.9 },
        3: { count: 0, percent: 0 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.9,
        agreement: 75.2,
      },
      Astringency: {
        0: { count: 28, percent: 53.8 },
        1: { count: 13, percent: 25 },
        2: { count: 9, percent: 17.3 },
        3: { count: 2, percent: 3.8 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.4,
        agreement: 53.2,
      },
      Aromaticity: {
        0: { count: 8, percent: 15.4 },
        1: { count: 9, percent: 17.3 },
        2: { count: 10, percent: 19.2 },
        3: { count: 21, percent: 40.4 },
        4: { count: 3, percent: 5.8 },
        5: { count: 1, percent: 1.9 },
        unanimity: 0.2,
        agreement: 44.2,
      },
      Texture: {
        0: { count: 7, percent: 13.5 },
        1: { count: 10, percent: 19.2 },
        2: { count: 12, percent: 23.1 },
        3: { count: 20, percent: 38.5 },
        4: { count: 3, percent: 5.8 },
        5: { count: 0, percent: 0 },
        unanimity: 0.2,
        agreement: 46.3,
      },
      Piquancy: {
        0: { count: 48, percent: 92.3 },
        1: { count: 2, percent: 3.8 },
        2: { count: 1, percent: 1.9 },
        3: { count: 1, percent: 1.9 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.8,
        agreement: 65.8,
      },
    },
    meanValues: {
      Sweetness: 3.25,
      Sourness: 2.04,
      Saltiness: 0.15,
      Bitterness: 0.29,
      Savoriness: 0.31,
      Fatness: 0.08,
      Astringency: 0.71,
      Aromaticity: 2.1,
      Texture: 2.04,
      Piquancy: 0.13,
    },
    STDValues: {
      Sweetness: 0.94,
      Sourness: 1.16,
      Saltiness: 0.5,
      Bitterness: 0.74,
      Savoriness: 0.8,
      Fatness: 0.33,
      Astringency: 0.88,
      Aromaticity: 1.26,
      Texture: 1.16,
      Piquancy: 0.52,
    },
  },
  {
    name: "Dark Chocolate",
    outliers: {
      Sweetness: [5],
      Sourness: [3, 4],
      Saltiness: [3],
      Bitterness: [0],
      Savoriness: [4, 5],
      Fatness: [],
      Astringency: [5],
      Aromaticity: [],
      Texture: [5],
      Piquancy: [4, 5],
    },
    distribution: {
      Sweetness: {
        0: { count: 17, percent: 25.4 },
        1: { count: 16, percent: 23.9 },
        2: { count: 15, percent: 22.4 },
        3: { count: 12, percent: 17.9 },
        4: { count: 4, percent: 6 },
        5: { count: 3, percent: 4.5 },
        unanimity: 0.1,
        agreement: 41.5,
      },
      Sourness: {
        0: { count: 46, percent: 68.7 },
        1: { count: 11, percent: 16.4 },
        2: { count: 5, percent: 7.5 },
        3: { count: 4, percent: 6 },
        4: { count: 1, percent: 1.5 },
        5: { count: 0, percent: 0 },
        unanimity: 0.5,
        agreement: 50.8,
      },
      Saltiness: {
        0: { count: 46, percent: 68.7 },
        1: { count: 14, percent: 20.9 },
        2: { count: 4, percent: 6 },
        3: { count: 3, percent: 4.5 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.5,
        agreement: 55.6,
      },
      Bitterness: {
        0: { count: 5, percent: 7.5 },
        1: { count: 4, percent: 6 },
        2: { count: 5, percent: 7.5 },
        3: { count: 13, percent: 19.4 },
        4: { count: 22, percent: 32.8 },
        5: { count: 18, percent: 26.9 },
        unanimity: 0.1,
        agreement: 40.3,
      },
      Savoriness: {
        0: { count: 42, percent: 62.7 },
        1: { count: 10, percent: 14.9 },
        2: { count: 9, percent: 13.4 },
        3: { count: 2, percent: 3 },
        4: { count: 3, percent: 4.5 },
        5: { count: 1, percent: 1.5 },
        unanimity: 0.4,
        agreement: 45.2,
      },
      Fatness: {
        0: { count: 16, percent: 23.9 },
        1: { count: 14, percent: 20.9 },
        2: { count: 8, percent: 11.9 },
        3: { count: 14, percent: 20.9 },
        4: { count: 11, percent: 16.4 },
        5: { count: 4, percent: 6 },
        unanimity: 0,
        agreement: 38.5,
      },
      Astringency: {
        0: { count: 37, percent: 55.2 },
        1: { count: 6, percent: 9 },
        2: { count: 4, percent: 6 },
        3: { count: 13, percent: 19.4 },
        4: { count: 6, percent: 9 },
        5: { count: 1, percent: 1.5 },
        unanimity: 0.3,
        agreement: 39.4,
      },
      Aromaticity: {
        0: { count: 13, percent: 19.4 },
        1: { count: 5, percent: 7.5 },
        2: { count: 11, percent: 16.4 },
        3: { count: 12, percent: 17.9 },
        4: { count: 15, percent: 22.4 },
        5: { count: 11, percent: 16.4 },
        unanimity: 0,
        agreement: 36.8,
      },
      Texture: {
        0: { count: 19, percent: 28.4 },
        1: { count: 16, percent: 23.9 },
        2: { count: 10, percent: 14.9 },
        3: { count: 12, percent: 17.9 },
        4: { count: 8, percent: 11.9 },
        5: { count: 2, percent: 3 },
        unanimity: 0.1,
        agreement: 40.2,
      },
      Piquancy: {
        0: { count: 62, percent: 92.5 },
        1: { count: 3, percent: 4.5 },
        2: { count: 0, percent: 0 },
        3: { count: 0, percent: 0 },
        4: { count: 1, percent: 1.5 },
        5: { count: 1, percent: 1.5 },
        unanimity: 0.8,
        agreement: 55.9,
      },
    },
    meanValues: {
      Sweetness: 1.69,
      Sourness: 0.55,
      Saltiness: 0.46,
      Bitterness: 3.45,
      Savoriness: 0.76,
      Fatness: 2.03,
      Astringency: 1.22,
      Aromaticity: 2.66,
      Texture: 1.7,
      Piquancy: 0.18,
    },
    STDValues: {
      Sweetness: 1.41,
      Sourness: 0.97,
      Saltiness: 0.8,
      Bitterness: 1.48,
      Savoriness: 1.21,
      Fatness: 1.6,
      Astringency: 1.54,
      Aromaticity: 1.72,
      Texture: 1.49,
      Piquancy: 0.79,
    },
  },
  {
    name: "Almonds",
    outliers: {
      Sweetness: [],
      Sourness: [3],
      Saltiness: [3],
      Bitterness: [5],
      Savoriness: [4, 5],
      Fatness: [0],
      Astringency: [],
      Aromaticity: [],
      Texture: [0],
      Piquancy: [3, 5],
    },
    distribution: {
      Sweetness: {
        0: { count: 9, percent: 36 },
        1: { count: 9, percent: 36 },
        2: { count: 4, percent: 16 },
        3: { count: 3, percent: 12 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.3,
        agreement: 50,
      },
      Sourness: {
        0: { count: 23, percent: 92 },
        1: { count: 1, percent: 4 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 4 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.8,
        agreement: 62.1,
      },
      Saltiness: {
        0: { count: 13, percent: 52 },
        1: { count: 8, percent: 32 },
        2: { count: 1, percent: 4 },
        3: { count: 3, percent: 12 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.4,
        agreement: 50.3,
      },
      Bitterness: {
        0: { count: 13, percent: 52 },
        1: { count: 6, percent: 24 },
        2: { count: 3, percent: 12 },
        3: { count: 2, percent: 8 },
        4: { count: 0, percent: 0 },
        5: { count: 1, percent: 4 },
        unanimity: 0.3,
        agreement: 44.2,
      },
      Savoriness: {
        0: { count: 15, percent: 60 },
        1: { count: 7, percent: 28 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 4 },
        4: { count: 1, percent: 4 },
        5: { count: 1, percent: 4 },
        unanimity: 0.4,
        agreement: 43.5,
      },
      Fatness: {
        0: { count: 2, percent: 8 },
        1: { count: 2, percent: 8 },
        2: { count: 3, percent: 12 },
        3: { count: 9, percent: 36 },
        4: { count: 4, percent: 16 },
        5: { count: 5, percent: 20 },
        unanimity: 0.1,
        agreement: 40.7,
      },
      Astringency: {
        0: { count: 12, percent: 48 },
        1: { count: 4, percent: 16 },
        2: { count: 4, percent: 16 },
        3: { count: 5, percent: 20 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.3,
        agreement: 45.5,
      },
      Aromaticity: {
        0: { count: 9, percent: 36 },
        1: { count: 7, percent: 28 },
        2: { count: 5, percent: 20 },
        3: { count: 4, percent: 16 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.3,
        agreement: 48.1,
      },
      Texture: {
        0: { count: 2, percent: 8 },
        1: { count: 0, percent: 0 },
        2: { count: 0, percent: 0 },
        3: { count: 3, percent: 12 },
        4: { count: 7, percent: 28 },
        5: { count: 13, percent: 52 },
        unanimity: 0.4,
        agreement: 42,
      },
      Piquancy: {
        0: { count: 23, percent: 92 },
        1: { count: 0, percent: 0 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 4 },
        4: { count: 0, percent: 0 },
        5: { count: 1, percent: 4 },
        unanimity: 0.8,
        agreement: 47.2,
      },
    },
    meanValues: {
      Sweetness: 1.04,
      Sourness: 0.16,
      Saltiness: 0.76,
      Bitterness: 0.92,
      Savoriness: 0.76,
      Fatness: 3.04,
      Astringency: 1.08,
      Aromaticity: 1.16,
      Texture: 4.08,
      Piquancy: 0.32,
    },
    STDValues: {
      Sweetness: 1,
      Sourness: 0.61,
      Saltiness: 0.99,
      Bitterness: 1.26,
      Savoriness: 1.3,
      Fatness: 1.46,
      Astringency: 1.2,
      Aromaticity: 1.08,
      Texture: 1.38,
      Piquancy: 1.12,
    },
  },
  {
    name: "Pear",
    outliers: {
      Sweetness: [],
      Sourness: [],
      Saltiness: [3],
      Bitterness: [3],
      Savoriness: [3],
      Fatness: [3],
      Astringency: [],
      Aromaticity: [],
      Texture: [],
      Piquancy: [3],
    },
    distribution: {
      Sweetness: {
        0: { count: 0, percent: 0 },
        1: { count: 2, percent: 16.7 },
        2: { count: 0, percent: 0 },
        3: { count: 6, percent: 50 },
        4: { count: 2, percent: 16.7 },
        5: { count: 2, percent: 16.7 },
        unanimity: 0.3,
        agreement: 45.2,
      },
      Sourness: {
        0: { count: 3, percent: 25 },
        1: { count: 3, percent: 25 },
        2: { count: 3, percent: 25 },
        3: { count: 3, percent: 25 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.2,
        agreement: 47.2,
      },
      Saltiness: {
        0: { count: 11, percent: 91.7 },
        1: { count: 0, percent: 0 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 8.3 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.8,
        agreement: 54.6,
      },
      Bitterness: {
        0: { count: 11, percent: 91.7 },
        1: { count: 0, percent: 0 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 8.3 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.8,
        agreement: 54.6,
      },
      Savoriness: {
        0: { count: 8, percent: 66.7 },
        1: { count: 2, percent: 16.7 },
        2: { count: 1, percent: 8.3 },
        3: { count: 1, percent: 8.3 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.5,
        agreement: 51.3,
      },
      Fatness: {
        0: { count: 10, percent: 83.3 },
        1: { count: 1, percent: 8.3 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 8.3 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.7,
        agreement: 54.1,
      },
      Astringency: {
        0: { count: 8, percent: 66.7 },
        1: { count: 0, percent: 0 },
        2: { count: 1, percent: 8.3 },
        3: { count: 1, percent: 8.3 },
        4: { count: 2, percent: 16.7 },
        5: { count: 0, percent: 0 },
        unanimity: 0.5,
        agreement: 38.3,
      },
      Aromaticity: {
        0: { count: 6, percent: 50 },
        1: { count: 2, percent: 16.7 },
        2: { count: 0, percent: 0 },
        3: { count: 3, percent: 25 },
        4: { count: 1, percent: 8.3 },
        5: { count: 0, percent: 0 },
        unanimity: 0.3,
        agreement: 40.3,
      },
      Texture: {
        0: { count: 4, percent: 33.3 },
        1: { count: 2, percent: 16.7 },
        2: { count: 1, percent: 8.3 },
        3: { count: 3, percent: 25 },
        4: { count: 2, percent: 16.7 },
        5: { count: 0, percent: 0 },
        unanimity: 0.2,
        agreement: 39.5,
      },
      Piquancy: {
        0: { count: 11, percent: 91.7 },
        1: { count: 0, percent: 0 },
        2: { count: 0, percent: 0 },
        3: { count: 1, percent: 8.3 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.8,
        agreement: 54.6,
      },
    },
    meanValues: {
      Sweetness: 3.17,
      Sourness: 1.5,
      Saltiness: 0.25,
      Bitterness: 0.25,
      Savoriness: 0.58,
      Fatness: 0.33,
      Astringency: 1.08,
      Aromaticity: 1.25,
      Texture: 1.75,
      Piquancy: 0.25,
    },
    STDValues: {
      Sweetness: 1.21,
      Sourness: 1.12,
      Saltiness: 0.83,
      Bitterness: 0.83,
      Savoriness: 0.95,
      Fatness: 0.85,
      Astringency: 1.61,
      Aromaticity: 1.48,
      Texture: 1.53,
      Piquancy: 0.83,
    },
  },
  {
    name: "Dark Coffee",
    outliers: {
      Sweetness: [3, 4],
      Sourness: [5, 4],
      Saltiness: [3, 2],
      Bitterness: [0],
      Savoriness: [3],
      Fatness: [2, 3],
      Astringency: [],
      Aromaticity: [],
      Texture: [3],
      Piquancy: [4, 3],
    },
    distribution: {
      Sweetness: {
        0: { count: 42, percent: 73.7 },
        1: { count: 10, percent: 17.5 },
        2: { count: 1, percent: 1.8 },
        3: { count: 3, percent: 5.3 },
        4: { count: 1, percent: 1.8 },
        5: { count: 0, percent: 0 },
        unanimity: 0.5,
        agreement: 52.6,
      },
      Sourness: {
        0: { count: 31, percent: 54.4 },
        1: { count: 12, percent: 21.1 },
        2: { count: 8, percent: 14 },
        3: { count: 4, percent: 7 },
        4: { count: 1, percent: 1.8 },
        5: { count: 1, percent: 1.8 },
        unanimity: 0.3,
        agreement: 45.9,
      },
      Saltiness: {
        0: { count: 49, percent: 86 },
        1: { count: 1, percent: 1.8 },
        2: { count: 5, percent: 8.8 },
        3: { count: 2, percent: 3.5 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.7,
        agreement: 56.5,
      },
      Bitterness: {
        0: { count: 4, percent: 7 },
        1: { count: 2, percent: 3.5 },
        2: { count: 4, percent: 7 },
        3: { count: 6, percent: 10.5 },
        4: { count: 13, percent: 22.8 },
        5: { count: 28, percent: 49.1 },
        unanimity: 0.2,
        agreement: 39.7,
      },
      Savoriness: {
        0: { count: 39, percent: 68.4 },
        1: { count: 12, percent: 21.1 },
        2: { count: 2, percent: 3.5 },
        3: { count: 4, percent: 7 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.5,
        agreement: 53.8,
      },
      Fatness: {
        0: { count: 45, percent: 78.9 },
        1: { count: 8, percent: 14 },
        2: { count: 3, percent: 5.3 },
        3: { count: 1, percent: 1.8 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.6,
        agreement: 60.6,
      },
      Astringency: {
        0: { count: 19, percent: 33.3 },
        1: { count: 3, percent: 5.3 },
        2: { count: 7, percent: 12.3 },
        3: { count: 17, percent: 29.8 },
        4: { count: 10, percent: 17.5 },
        5: { count: 1, percent: 1.8 },
        unanimity: 0.2,
        agreement: 38.6,
      },
      Aromaticity: {
        0: { count: 10, percent: 17.5 },
        1: { count: 1, percent: 1.8 },
        2: { count: 4, percent: 7 },
        3: { count: 12, percent: 21.1 },
        4: { count: 16, percent: 28.1 },
        5: { count: 14, percent: 24.6 },
        unanimity: 0.1,
        agreement: 36.8,
      },
      Texture: {
        0: { count: 41, percent: 71.9 },
        1: { count: 5, percent: 8.8 },
        2: { count: 7, percent: 12.3 },
        3: { count: 4, percent: 7 },
        4: { count: 0, percent: 0 },
        5: { count: 0, percent: 0 },
        unanimity: 0.5,
        agreement: 51,
      },
      Piquancy: {
        0: { count: 50, percent: 87.7 },
        1: { count: 3, percent: 5.3 },
        2: { count: 0, percent: 0 },
        3: { count: 2, percent: 3.5 },
        4: { count: 2, percent: 3.5 },
        5: { count: 0, percent: 0 },
        unanimity: 0.7,
        agreement: 52.1,
      },
    },
    meanValues: {
      Sweetness: 0.44,
      Sourness: 0.86,
      Saltiness: 0.3,
      Bitterness: 3.86,
      Savoriness: 0.49,
      Fatness: 0.3,
      Astringency: 1.98,
      Aromaticity: 3.14,
      Texture: 0.54,
      Piquancy: 0.3,
    },
    STDValues: {
      Sweetness: 0.9,
      Sourness: 1.18,
      Saltiness: 0.77,
      Bitterness: 1.52,
      Savoriness: 0.86,
      Fatness: 0.65,
      Astringency: 1.59,
      Aromaticity: 1.72,
      Texture: 0.96,
      Piquancy: 0.92,
    },
  },
];

export const ZGlyphData = [
  {
    baselineMean: {
      Sweetness: 1.04,
      Sourness: 0.16,
      Saltiness: 0.76,
      Bitterness: 0.92,
      Savoriness: 0.76,
      Fatness: 3.04,
      Astringency: 1.08,
      Aromaticity: 1.16,
      Texture: 4.08,
      Piquancy: 0.32,
    },
    baselineStDev: {
      Sweetness: 1,
      Sourness: 0.61,
      Saltiness: 0.99,
      Bitterness: 1.26,
      Savoriness: 1.3,
      Fatness: 1.46,
      Astringency: 1.2,
      Aromaticity: 1.08,
      Texture: 1.38,
      Piquancy: 1.12,
    },
    compareMean: {
      Sweetness: 1,
      Sourness: 0.1,
      Saltiness: 0.5,
      Bitterness: 0.6,
      Savoriness: 1.4,
      Fatness: 4.2,
      Astringency: 1.6,
      Aromaticity: 1.9,
      Texture: 4.5,
      Piquancy: 0.8,
    },
    compareSTDValues: {
      Sweetness: 0.63,
      Sourness: 0.3,
      Saltiness: 0.92,
      Bitterness: 0.8,
      Savoriness: 1.62,
      Fatness: 0.87,
      Astringency: 1.02,
      Aromaticity: 0.83,
      Texture: 0.67,
      Piquancy: 1.66,
    },
  },
  {
    Sweetness: { 0: { count: 2 }, 1: { count: 6 }, 2: { count: 2 }, 3: { count: 0 }, 4: { count: 0 }, 5: { count: 0 } },
    Saltiness: { 0: { count: 7 }, 1: { count: 2 }, 2: { count: 0 }, 3: { count: 1 }, 4: { count: 0 }, 5: { count: 0 } },
    Sourness: { 0: { count: 9 }, 1: { count: 1 }, 2: { count: 0 }, 3: { count: 0 }, 4: { count: 0 }, 5: { count: 0 } },
    Bitterness: { 0: { count: 6 }, 1: { count: 2 }, 2: { count: 2 }, 3: { count: 0 }, 4: { count: 0 }, 5: { count: 0 } },
    Savoriness: { 0: { count: 3 }, 1: { count: 5 }, 2: { count: 0 }, 3: { count: 0 }, 4: { count: 1 }, 5: { count: 1 } },
    Fatness: { 0: { count: 0 }, 1: { count: 0 }, 2: { count: 0 }, 3: { count: 3 }, 4: { count: 2 }, 5: { count: 5 } },
    Astringency: { 0: { count: 2 }, 1: { count: 2 }, 2: { count: 4 }, 3: { count: 2 }, 4: { count: 0 }, 5: { count: 0 } },
    Aromaticity: { 0: { count: 0 }, 1: { count: 4 }, 2: { count: 3 }, 3: { count: 3 }, 4: { count: 0 }, 5: { count: 0 } },
    Texture: { 0: { count: 0 }, 1: { count: 0 }, 2: { count: 0 }, 3: { count: 1 }, 4: { count: 3 }, 5: { count: 6 } },
    Piquancy: { 0: { count: 8 }, 1: { count: 0 }, 2: { count: 0 }, 3: { count: 1 }, 4: { count: 0 }, 5: { count: 1 } },
  },
];
